version: "3.8"
services:
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 8080:80
    depends_on:
      - backend
  backend:
    build: flask
    container_name: flask
    environment: 
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    depends_on:
      -  mongo  
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    ports:
      - 27017
    volumes: 
      - ./mongo/database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
  webngin:
    image: nginx
    container_name: nginx_client
    ports:
     - 80:80
    volumes:
      - ./nginx_client:/usr/share/nginx/html
    depends_on: 
      - web
